#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Linting and formatting"
npm run prettier
npm run lint

echo "Running local unit test"
npm run test

# capture prettier and linting changes
git add .